name: 'Build and Deploy'

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Create .env'
        run: touch .env

      - name: 'Install composer dependencies'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: 'Install npm dependencies'
        run: npm ci

      - name: 'Generate key'
        run: php artisan key:generate

      - name: 'Export website'
        run: php artisan export

      - name: 'Deploy'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: Update website
